FROM registry.fedoraproject.org/fedora-toolbox:44

RUN dnf -y upgrade \
    && dnf clean all

# Core of this image: required stuff for emacs
RUN dnf -y install \
    emacs-pgtk \
    flatpak-xdg-open \
    adw-gtk3-theme \
    google-noto-color-emoji-fonts \
    gdk-pixbuf2-modules-extra \
    jetbrains-mono-fonts-all \
    wl-clipboard \
    direnv \
    hunspell-en \
    hunspell-fr \
    enchant2-devel \
    locate \
    pandoc \
    stow \
    podman-remote \
    && dnf clean all

# Mail in Emacs
RUN dnf -y install \
    mu \
    isync \
    msmtp && \
    dnf clean all

WORKDIR /tmp

# Installing cyrus-sasl-xoauth2 for oauth authentication
RUN dnf install -y cyrus-sasl-devel automake libtool && \
    git clone https://github.com/moriyoshi/cyrus-sasl-xoauth2 && \
    cd cyrus-sasl-xoauth2/ && \
    ./autogen.sh && \
    ./configure && \
    make install && \
    mv /usr/lib/sasl2/* /usr/lib64/sasl2/ && \
    rmdir /usr/lib/sasl2 && \
    dnf remove -y cyrus-sasl-devel automake libtool && \
    dnf clean all

WORKDIR /tmp
RUN dnf install -y rustc cargo && \
    git clone https://github.com/ltratt/pizauth && \
    cd pizauth && \
    make install && \
    dnf remove -y rustc cargo && \
    dnf clean all

RUN rm -rf /tmp/*
