FROM registry.fedoraproject.org/fedora-toolbox:rawhide AS emacs

RUN dnf -y upgrade && \
    dnf -y install \
        emacs-pgtk \
        flatpak-xdg-open \
        adw-gtk3-theme \
        google-noto-color-emoji-fonts \
        gdk-pixbuf2-modules-extra \
        jetbrains-mono-fonts-all \
    && dnf clean all \
    && ln -sf /usr/bin/podman-remote /usr/bin/podman

FROM emacs as lang_toolchains

# LaTeX
RUN dnf -y install \
        texlive-scheme-medium \
        texlive-collection-latex \
        texlive-collection-latexrecommended \
        texlive-collection-latexextra \
        texlive-collection-fontsrecommended \
        texlive-pgf \
        texlive-e-french \
        texlive-collection-langenglish \
        texlive-collection-langfrench \
        texlive-collection-xetex \
        texlive-collection-luatex \
        texlive-apacite \
    && dnf clean all

WORKDIR /tmp
ARG LTEX_LS_PLUS_VERSION="18.7.0"
ARG LTEX_LS_PLUS_URL="https://github.com/ltex-plus/ltex-ls-plus/releases/download/${LTEX_LS_PLUS_VERSION}/ltex-ls-plus-${LTEX_LS_PLUS_VERSION}-linux-x64.tar.gz"
# ltex-ls-plus for grammar checking
RUN curl -o ltex-ls-plus.tar.gz -L ${LTEX_LS_PLUS_URL} \
    && tar -xvf ltex-ls-plus.tar.gz  -C /usr/local --no-same-owner --no-overwrite-dir \
    && ln -s /usr/local/ltex-ls-plus-*/bin/ltex-ls-plus /usr/local/bin/ltex-ls-plus \
    && rm ltex-ls-plus.tar.gz

# Python
RUN dnf -y install python-pip \
    && dnf clean all \
    && pip install --no-cache-dir pyright

# Racket
RUN dnf -y install \
    racket \
    # Needed for raco
    openssl-devel \
    && dnf clean all

RUN yes a | raco pkg install -i racket-langserver

# R
RUN dnf -y install R \
    && dnf clean all

WORKDIR /tmp
ENV ZIG_VERSION=0.16.0
# Zig
RUN dnf -y install zig && \
    curl -LO https://builds.zigtools.org/zls-x86_64-linux-${ZIG_VERSION}.tar.xz && \
    tar -xvf zls-x86_64-linux-${ZIG_VERSION}.tar.xz && \
    cp zls /usr/bin

# C/CPP
RUN dnf -y group install development-tools \
    && dnf -y install \
        # Needed for conan...
        perl-core \
        clang-tools-extra \
        cmake \
        meson \
        make \
        g++ \
        gdb \
        bear \
        perf \
    && dnf clean all

FROM lang_toolchains AS misc_tools
RUN dnf -y install \
        pandoc \
        stow \
        wl-clipboard \
        direnv \
        hunspell-en \
        hunspell-fr \
        locate \
        podman-remote \
        hugo \
    && dnf clean all

FROM misc_tools AS finishing_touches
RUN mandb && updatedb
RUN rm -r /tmp/*
RUN find /usr/share/emacs/site-lisp/ -name "*.el" -exec sed -i '1i\;; -*- lexical-binding: nil; -*-' {} +
